# Generated by Django 5.0 on 2023-12-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('address', models.CharField(max_length=1024, verbose_name='Адрес')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_by_creator', to='extended_user.profile', verbose_name='Создатель')),
                ('last_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_by_last_editor', to='extended_user.profile', verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'unique_together': {('name', 'address')},
            },
        ),
    ]
