# Generated by Django 5.0 on 2023-12-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование')),
                ('measure_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measure', verbose_name='Единица измерения')),
            ],
        ),
    ]
