# Generated by Django 5.0 on 2023-12-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='С')),
                ('end_date', models.DateField(verbose_name='По')),
                ('status', models.CharField(choices=[('in_progress', 'Генерация'), ('OK', 'Сгенерирован'), ('error', 'Ошибка генерации')], max_length=1024, verbose_name='Статус')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_by_creator', to='extended_user.profile', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
