# Generated by Django 5.0 on 2023-12-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Генерация'), ('OK', 'Сгенерирован'), ('error', 'Ошибка генерации')], default='in_progress', max_length=1024, verbose_name='Статус'),
        ),
    ]
