# Generated by Django 5.0 on 2023-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(verbose_name='От'),
        ),
    ]
