# Generated by Django 5.0 on 2023-12-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_end_date_alter_report_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время генерации'),
        ),
    ]
