# Generated by Django 4.2.5 on 2023-09-12 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание профиля')),
                ('university', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место учебы')),
                ('communication', models.CharField(blank=True, max_length=200, null=True, verbose_name='Другие способы коммуникации')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания учетной записи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'unique_together': {('name', 'surname', 'patronymic')},
            },
        ),
    ]
