# Generated by Django 5.0 on 2023-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0002_remove_profile_university_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='communication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контакты'),
        ),
    ]
