# Generated by Django 5.0 on 2023-12-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admission', 'Поступление'), ('departure', 'Убытие'), ('transfer', 'Передача'), ('recalc', 'Переучет')], max_length=1024)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date', models.DateField(verbose_name='Дата операции')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_by_creator', to='extended_user.profile', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'default_related_name': 'operations',
            },
        ),
    ]
