# Generated by Django 5.0 on 2023-12-08 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
        ('operation', '0001_initial'),
        ('product', '0003_product_creator_product_last_editor'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='from_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_stocks', to='stock.stock', verbose_name='Исходный склад'),
        ),
        migrations.AddField(
            model_name='operation',
            name='last_editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_by_editor', to='extended_user.profile', verbose_name='Последний редактор'),
        ),
        migrations.AddField(
            model_name='operation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='operation',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='stock.stock', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='operation',
            name='to_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_stocks', to='stock.stock', verbose_name='Новый склад'),
        ),
    ]
