# Generated by Django 5.0 on 2023-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
