# Generated by Django 5.0 on 2023-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_operation_cost_alter_operation_from_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
