# Generated by Django 5.0 on 2023-12-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together={('name',)},
        ),
    ]
